[package]
name = "color_palette"
version = "0.1.0"
authors = ["Clark Moody <clark@clarkmoody.com>"]
edition = "2018"
publish = false

[features]
palette = []

[dependencies]
iced = { path = "../..", features = ["palette"] }
iced_core = { path = "../../core" }
iced_native = { path = "../../native" }
