[package]
name = "radio"
version = "0.1.0"
authors = ["Aaron Honeycutt <aaronhoneycutt@proton.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { path = "../.." }
