[package]
name = "iced_web_tour"
version = "0.0.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
iced_web = { path = "../.." }
wasm-bindgen = "0.2.50"
futures-preview = "=0.3.0-alpha.18"
log = "0.4"
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"
