[package]
name = "pure_color_palette"
version = "0.1.0"
authors = ["Clark Moody <clark@clarkmoody.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { path = "../../..", features = ["pure", "canvas", "palette"] }
palette = "0.6.0"
