[package]
name = "iced_native"
version = "0.1.0-alpha"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A renderer-agnostic library for native GUIs"
license = "MIT"
repository = "https://github.com/hecrj/iced"

[package.metadata.docs.rs]
features = ["winit"]

[dependencies]
iced_core = { version = "0.1.0-alpha", path = "../core" }
stretch = "0.2"
twox-hash = "1.5"
raw-window-handle = "0.1"

# Enable to obtain conversion traits
winit = { version = "0.20.0-alpha3", optional = true }
