[package]
name = "iced_renderer"
version = "0.1.0"
edition = "2021"

[features]
image = ["iced_wgpu/image", "iced_tiny_skia/image"]
svg = ["iced_wgpu/svg", "iced_tiny_skia/svg"]
canvas = ["iced_wgpu/canvas", "iced_tiny_skia/canvas"]
qr_code = ["canvas", "qrcode"]
tracing = ["iced_wgpu/tracing"]

[dependencies]
raw-window-handle = "0.5"
thiserror = "1"

[dependencies.iced_native]
version = "0.9"
path = "../native"

[dependencies.iced_graphics]
version = "0.7"
path = "../graphics"

[dependencies.iced_tiny_skia]
version = "0.1"
path = "../tiny_skia"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iced_wgpu = { version = "0.9", path = "../wgpu" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced_wgpu = { version = "0.9", path = "../wgpu", features = ["webgl"] }

[dependencies.qrcode]
version = "0.12"
optional = true
default-features = false
