[package]
name = "iced_winit"
version = "0.1.0-alpha"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A winit runtime for Iced"
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced_winit"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[features]
debug = []

[dependencies]
winit = "0.22"
log = "0.4"

[dependencies.iced_native]
version = "0.1.0-alpha"
path = "../native"

[dependencies.window_clipboard]
git = "https://github.com/hecrj/window_clipboard"
rev = "22c6dd6c04cd05d528029b50a30c56417cd4bebf"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.6"
