name: Detect
on:
  push: {}
  pull_request: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  outdated_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - name: Install cargo-outdated
      run: cargo install cargo-outdated
    - uses: actions/checkout@master
    - name: Detect outdated dependencies
      run: cargo outdated --exit-code 1
